version: "3.2"

services:
  # Seemingly to be the second stage of building after .devcontainer/Dockerfile completes
  # See https://www.baeldung.com/ops/multiple-dockerfiles
  vscode:
    build: .
    image: latexdevcontainer
    volumes:
      # The home directory is called "workspace"; try `cd ..` and `ls` to figure it out.
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/root/.ssh
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig
    environment:
      - TZ=TW
      # Set the timezone
    entrypoint: sh -c "chmod a+w projects && cd projects && chmod -R a+w * && sleep infinity"
